# -*- coding: utf-8 -*-
"""BCGX Gen AI Data Extraction and Initial Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uG6tJ1uBwYIYn-GySQUPLEsjKcxKh3tT

### Importing the necessary Modules
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

"""### Reading the Manually Extracted Dataset from SEC's EDGAR's database
### <a href>https://www.sec.gov/edgar/searchedgar/cik</a>
"""

data = pd.read_csv('/content/Final.csv')

data



"""### Calculating Year-by-Year growth rates for Total Revenue and Net Income"""

data['Revenue Growth (%)'] = data.groupby('Company')['Total Revenue'].pct_change() * 100
data['Net Income Growth (%)'] = data.groupby('Company')['Net Income'].pct_change() * 100

data

"""### Imputing Null/NaN values that result from pct_change calculations with 0"""

data.fillna(0, inplace=True)

data

"""### Calculating Year-by-Year growth rates for Total Assets, Total Liabilities and Cash flow from Operations Activities"""

data['Assets Growth (%)'] = data.groupby('Company')['Total Assets'].pct_change() * 100
data['Liabilities Growth (%)'] = data.groupby('Company')['Total Liabilities'].pct_change() * 100
data['Cash Flow from Operations Growth(%)'] = data.groupby('Company')['Cash Flow from Operating Activities'].pct_change() * 100

data

data.fillna(0, inplace=True)

data

data.to_csv('final_data_report.csv')

mean_growth = data.groupby('Company')[['Revenue Growth (%)', 'Net Income Growth (%)', 'Assets Growth (%)', 'Liabilities Growth (%)', 'Cash Flow from Operations Growth(%)']].mean().reset_index()

print('Year-By-Year Average Growth Rates(%) :-')
print('             OR')
print("Overall Growth/Fall rate for Apple, Microsoft and Tesla from Fiscal Year 2021 - 2023")
mean_growth



# prompt: Using dataframe summary: barplot

import altair as alt
alt.Chart(mean_growth).mark_bar().encode(
    alt.X('Company:N', title='Company'),
    alt.Y('Revenue Growth (%):Q', title='Revenue Growth (%)'),
    color='Company:N',
).properties(width=alt.Step(80)).interactive()

mean_growth.to_csv('Summary_final_report.csv')

"""
#This task involves Manual extraction of Financial Statements of Microsoft, Apple and Tesla for the fiscal year 2021, 2022 and 2023 respectively.

# I completed my this task by following these steps :-

#1. Organizing  Data:
Ensure that dataset is structured properly with columns for Year, Company,	Total Revenue,	Net Income, Total Assets,	Total Liabilities,	Cash Flow from Operating Activities
#2. Calculate Year-over-Year Percentage Change:
Use the pct_change() function to calculate the percentage change for each metric year-over-year within each company group.
#3. Handle Missing Values:
The pct_change() function will result in NaN for the first year of each company since there is no previous year to compare. Decide how you want to handle these NaN values (e.g., removing them or replacing them with 0 or another value).
#4. Calculate the Mean of Percentage Changes:
After calculating the percentage changes, find the mean of these changes across all years for each company.


"""

